stages:
    - prepare
    - test
    - build

default:
    image: node:15.14.0-stretch
    before_script:
        - npm set cache .npm
        - npm install --prefer-offline --no-audit
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .npm/
            - node_modules/

install-node-deps:
    stage: prepare
    before_script:
        - node --version
        - npm --version
    script:
        - npm ci --cache .npm --prefer-offline
    only:
        changes:
            - package*.json

lint:
    stage: test
    script:
        - npm run lint

build-frontend:
    stage: build
    script:
        - npm run build
        - mkdir -p dist/ecloud-dashboard
        - cp -a appinfo l10n lib css img js  dist/ecloud-dashboard
    artifacts:
        paths:
            - dist/ecloud-dashboard
