stages:
    - prepare
    - test
    - build
    - deploy

default:
    image: node:15.14.0-stretch
    before_script:
        - npm set cache .npm
        - npm install --prefer-offline --no-audit
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .npm/
            - node_modules/

install-node-deps:
    stage: prepare
    before_script:
        - node --version
        - npm --version
    script:
        - npm set cache .npm
        - npm ci
    only:
        changes:
            - package*.json

lint:
    stage: test
    script:
        - npm run lint

build-frontend:
    stage: build
    script:
        - npm run build
        - mkdir -p dist/ecloud-dashboard
        - cp -a appinfo css l10n lib templates js dist/ecloud-dashboard
    artifacts:
        paths:
            - dist/ecloud-dashboard

.deploy:ecloud-dashboard:
    image: ubuntu:focal
    stage: deploy
    before_script:
      - mkdir $HOME/.ssh
      - chmod 700 ~/.ssh
      - echo "$SSH_PRIVATE_KEY_ED" > $HOME/.ssh/id_ed25519
      - echo "$SSH_PUBKEY_ED" > $HOME/.ssh/id_ed25519.pub
      - echo "$SSH_KNOWN_HOSTS" > $HOME/.ssh/known_hosts
      - chmod 600 ~/.ssh/id_ed25519
      - chmod 644 ~/.ssh/known_hosts ~/.ssh/id_ed25519.pub
      - apt-get update && apt-get install -y openssh-client
    script:
      - echo "Deploying to $CI_ENVIRONMENT_NAME ($DEPLOYMENT_HOST)"
      - ssh $SSH_USER@$DEPLOYMENT_HOST "git clone --depth 1 $CI_REPOSITORY_URL --branch $DEPLOYMENT_BRANCH --single-branch /tmp/${CI_JOB_ID}/ecloud-dashboard && && sudo docker exec -u www-data $CONTAINER_NAME /var/www/html/occ app:disable ecloud-dashboard && sudo rsync -avzh --chown www-data:www-data --delete --exclude '.git*' /tmp/${CI_JOB_ID}/ecloud-dashboard ${DEPLOYMENT_PATH}/html/custom_apps/ && rm -rf /tmp/${CI_JOB_ID} && sudo docker exec -u www-data $CONTAINER_NAME /var/www/html/occ app:enable ecloud-dashboard"


deploy:dev01:
    extends: .deploy:ecloud-dashboard
    only:
      - master
      - main
      - production
    environment:
      name: dev/01
      url: https://dev.eeo.one/
    variables:
      DEPLOYMENT_BRANCH: $CI_COMMIT_BRANCH
      CONTAINER_NAME: dev01_nextcloud

deploy:dev02:
  extends: .deploy:ecloud-dashboard
  when: manual
  only:
    - master
    - main
    - production
  environment:
    name: dev/02
    url: https://ecloud02.dev.eeo.one
  variables:
    DEPLOYMENT_BRANCH: $CI_COMMIT_BRANCH
    CONTAINER_NAME: dev02_nextcloud

deploy:dev03:
  extends: .deploy:ecloud-dashboard
  when: manual
  only:
    - master
    - main
    - production
  environment:
    name: dev/03
    url: https://ecloud03.dev.eeo.one
  variables:
    DEPLOYMENT_BRANCH: $CI_COMMIT_BRANCH
    CONTAINER_NAME: dev03_nextcloud

deploy:staging:
  extends: .deploy:ecloud-dashboard
  when: manual
  only:
    - master
    - main
    - production
  environment:
    name: staging/01
    url: https://eeo.one
  variables:
    DEPLOYMENT_BRANCH: $CI_COMMIT_BRANCH
    CONTAINER_NAME: nextcloud
