stages:
    - prepare
    - test
    - build
    - deploy

default:
    image: node:15.14.0-stretch
    before_script:
        - npm set cache .npm
        - npm install --prefer-offline --no-audit
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .npm/
            - node_modules/

install-node-deps:
    stage: prepare
    before_script:
        - node --version
        - npm --version
    script:
        - npm set cache .npm
        - npm ci
    only:
        changes:
            - package*.json

include:
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/template
    file: "nc-apps-build-frontend.yml"
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/template
    file: "nc-apps-deploy.yml"
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/template
    file: "nc-apps-lint.yml"

lint:
  stage: test
  script:
    - npm run lint -- --fix


build-frontend:
  stage: build

.deploy:nextcloud-app:
  stage: deploy
  dependencies:
    - build-frontend
  after_script:
    - ssh $SSH_USER@$DEPLOYMENT_HOST "sudo rsync -avzh --chown www-data:www-data --delete /tmp/${CI_JOB_ID}/$CI_PROJECT_NAME ${DEPLOYMENT_PATH}/html/custom_apps/ && rm -rf /tmp/${CI_JOB_ID} && sudo docker exec -u www-data $CONTAINER_NAME /var/www/html/occ app:enable $CI_PROJECT_NAME"
