variables:
    APP_NAME: 'murena-dashboard'
    TO_PACKAGE: 'appinfo l10n lib templates js'

include:
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: main
    file: "nc-apps-lint-build-frontend.yml"
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: main
    file: "nc-apps-deploy.yml"
