include:
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/template
    file: "nc-apps-build-frontend.yml"
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/nc-apps-checkout-deploy
    file: "nc-apps-checkout-deploy.yml"
  - project: "e/infra/ecloud/nextcloud-apps/ci-templates"
    ref: dev/template
    file: "nc-apps-lint.yml"

lint:
  stage: test
  script:
    - npm run lint -- --fix


build-frontend:
  stage: build

.deploy:nextcloud-app-by-checkout:
  stage: deploy
  dependencies:
    - build-frontend
  after_script:
    - ssh $SSH_USER@$DEPLOYMENT_HOST "sudo rsync -avzh --chown www-data:www-data --delete /tmp/${CI_JOB_ID}/$CI_PROJECT_NAME ${DEPLOYMENT_PATH}/html/custom_apps/ && rm -rf /tmp/${CI_JOB_ID} && sudo docker exec -u www-data $CONTAINER_NAME /var/www/html/occ app:enable $CI_PROJECT_NAME"
